# -*- coding: utf-8 -*-
"""
Django settings for myblog project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'kk+w_4tejxf8rtczx8s^1#a*d6f8+u=!#7$%r0l$26tf517&em'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',  #
    'api.cms',  #
    'api.common',  #
    'api.front',  #
    'article',  #
    'cmsauth',  #
    'frontauth',  #
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'frontauth.middlewares.AuthMiddleware'  #
]

ROOT_URLCONF = 'myblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'contextprocessor.cms_contextprocessor.CmsContextProcessor',
                'frontauth.context_processors.auth'
            ],
        },
    },
]

WSGI_APPLICATION = 'myblog.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# CACHES
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': [
            '127.0.0.1:11211',
        ]
    }
}

# session
# SESSION_EXPIRE_AT_BROWSER_CLOSE=True
# SESSION_ENGINE = 'django.contrib.sessions.backends.file'
# SESSION_FILE_PATH = 'api'
# SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
# 先保存在缓存当中,然后再同步到数据库中
# SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
# 1. 现在数据库是空的,如果我们登陆以后,数据库中出现了新的session数据,说明我们的session
# 数据同步到数据库中了
# 2. 如果我们把数据库中的session数据删除了,但是用户还能继续操作需要登录的界面,
# 说明缓存当中也保存了一份session数据.


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

LOGIN_URL = '/cms/login/'

# email config
# EMAIL_HOST_PASSWORD = 'iftlyqngoflvcaje'
# EMAIL_HOST_USER = '27331032@qq.com'
# EMAIL_HOST = 'smtp.qq.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True

# xiaoweizbc的163邮箱
# EMAIL_HOST_PASSWORD = 'xiaoweizbc2017'
# EMAIL_HOST_USER = 'xiaoweizbc@163.com'
# EMAIL_HOST = 'smtp.163.com'
# EMAIL_PORT = 25  # ssl:465/994 !ssl:25（只有25有效）
# EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = 'xiaoweizbc@163.com'

# Fantastic的qq邮箱
EMAIL_HOST_PASSWORD = 'tbiuzypicmsybiid'
EMAIL_HOST_USER = '358083856@qq.com'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# number of page
NUM_PAGE = 10
